apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ template "app.name" . }}"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "app.labels" . | nindent 8 }}
      annotations:
{{- if .Values.podAnnotations }}
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
    spec:
      securityContext:
        {{- include "app.securitycontext" . | nindent 8 }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecrets }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ default .Chart.AppVersion .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        env:
          {{- $podAnnotations := default dict .Values.podAnnotations }}
          {{- $injectionEnabled := eq (default "false" (index $podAnnotations "inject.xfsc.io/enabled")) "true" }}

          {{- if not $injectionEnabled }}
          - name: "SIGNER_CREDENTIAL_URL"
            value: {{ .Values.config.signerUrl }}
          - name: "NATS_REQUEST_TIMEOUT"
            value: {{ .Values.config.nats.requestTimeOut }} 
          - name: "NATS_URL"
            value: {{ .Values.config.nats.url }}
          {{- end }}

          - name: "CREDENTIAL_ISSUER"
            value: {{ .Values.config.credential_issuer }}
          - name: "AUTHORIZATION_SERVER"
            value: "{{ join "," .Values.config.authorization_server }}"
          - name: "CREDENTIAL_ENDPOINT"
            value: {{ .Values.config.credential_endpoint }}
          - name: "NATS_QUEUE_GROUP"
            value: {{ .Values.config.nats.queuegroup }}      
          - name: "HTTP_HOST"
            value: {{ .Values.server.http.host | quote }}
          - name: "HTTP_PORT"
            value: {{ .Values.server.http.port | quote }}
                
        ports:
        - name: http
          containerPort: {{ .Values.server.http.port }}
        readinessProbe:
          httpGet:
            path: /health
            port: {{ .Values.server.http.port }}
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 2
          failureThreshold: 2
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.server.http.port }}
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 3
          timeoutSeconds: 5
