apiVersion: v2
appVersion: v1.0.0
description: Dummy Content Signer
name: dummycontentsigner
version: 1.0.2-tag
dependencies:
  - name: library
    version: 1.1.1
    repository: oci://node-654e3bca7fbeeed18f81d7c7.ps-xaas.io/dev-ops
